#
# qmake configuration for amiga-g++
#

MAKEFILE_GENERATOR      = UNIX
QMAKE_PLATFORM          = amiga

# Addon software goes into /usr/local on AmigaOS, by default we will look there

CROSS_COMPILE           = ppc-amigaos-

include(../common/gcc-base.conf)
include(../common/gcc-base-unix.conf)
include(../common/g++-unix.conf)
include(../common/unix.conf)

QMAKE_CFLAGS_STATIC_LIB    -= $$QMAKE_CFLAGS_PIC
QMAKE_CFLAGS_APP           -= $$QMAKE_CFLAGS_PIC
QMAKE_CXXFLAGS_STATIC_LIB    -= $$QMAKE_CFLAGS_PIC
QMAKE_CXXFLAGS_APP           -= $$QMAKE_CFLAGS_PIC

# Add modifications here
QMAKE_CFLAGS            += -mcrt=clib4
QMAKE_CXXFLAGS          += -std=c++17 -mcrt=clib4
QMAKE_LFLAGS            += -athread=native -mcrt=clib4
QMAKE_LFLAGS_APP        += -Wl,--export-dynamic -Wl,-rpath-link=/qt6-amiga/lib -Wl,--no-undefined
QMAKE_LIBS              += -licui18n -licuuc -licudata -lssl -lcrypto -lpthread -latomic -lauto
QMAKE_LIBS_OPENGL       =
QMAKE_LIBS_OPENGL_ES2   =

QMAKE_AR                = ar cqs
QMAKE_OBJCOPY           = objcopy
QMAKE_NM                = nm -P
QMAKE_RANLIB            =

load(qt_config)
